server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

forest:
  max-connections: 1000
  connect-timeout: 60000
  read-timeout: 60000
  log-enabled: true
  log-request: true
  log-response-content: true